const {chromium}=require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const fs=require('node:fs');
(async()=>{
 const browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_EXECUTABLE});
 const page=await browser.newPage({viewport:{width:1512,height:1100},deviceScaleFactor:1});
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('http://127.0.0.1:8787/?demo=1');
 await page.getByText('DEMO / 演示模式',{exact:false}).waitFor();
 await page.waitForFunction(()=>document.querySelectorAll('#sector-rows tr').length>1);
 await page.screenshot({path:'artifacts/dashboard-desktop.png',fullPage:true});
 await page.getByRole('tab',{name:/B.*趋势启动池/}).click();
 const rows=await page.locator('#stock-rows button').count();
 if(rows===0)throw new Error('No demo stocks in B');
 await page.locator('#stock-rows button').first().click();
 await page.locator('#detail[open]').waitFor();
 if(await page.locator('#detail svg').count()!==1)throw new Error('No candlestick chart');
 await page.screenshot({path:'artifacts/dashboard-detail.png'});
 await page.getByRole('button',{name:'关闭详情'}).click();
 await page.selectOption('#risk-filter','高');
 await page.selectOption('#risk-filter','');
 const phone=await browser.newPage({viewport:{width:390,height:844},deviceScaleFactor:1,isMobile:true,hasTouch:true});
 await phone.goto('http://127.0.0.1:8787/?demo=1');
 await phone.waitForFunction(()=>document.querySelectorAll('#sector-rows tr').length>1);
 await phone.getByRole('tab',{name:/B.*趋势启动池/}).click();
 await phone.screenshot({path:'artifacts/dashboard-mobile.png',fullPage:true});
 const overflow=await phone.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth);
 if(overflow)throw new Error('Page horizontal overflow');
 await page.goto('http://127.0.0.1:8787/');
 await page.waitForFunction(()=>document.querySelector('#environment').textContent==='待确认');
 if(await page.locator('#mode-banner').isVisible())throw new Error('Demo shown in production');
 const result={desktop:'PASS',mobile:'PASS',stock_detail:'PASS',filters:'PASS',production_empty_state:'PASS',javascript_errors:errors,stock_rows:rows};
 fs.writeFileSync('artifacts/dashboard-check.json',JSON.stringify(result,null,2));
 console.log(JSON.stringify(result));
 await browser.close();if(errors.length)process.exitCode=1;
})().catch(e=>{console.error(e);process.exitCode=1;});
